name: InteractionsQuests
version: 1.1
description: Quests module for Interactions
author: Browsit
website: https://github.com/Browsit/InteractionsQuestsModule

main: org.browsit.interactionsquests
depend: [Interactions, Quests]